#!/bin/bash

for i in {1..10}
do
   echo " Value of i is $i"
   if [ $i == 5 ] 
   then
       continue #Break We can use Break or Continue Here
   fi
done

#Break Statement is used to break the iterations
#Continue Statement is used to continue the iteration without getting pause the condition.
